-- create table users (
--     id uuid primary key,
--     login_identifier varchar(150) not null unique,
--     password_hash varchar(255) not null,
--     full_name varchar(255),
--     role varchar(32) not null,
--     account_status varchar(32) not null,
--     last_login_at timestamp null
-- );
--
-- create table login_audit_logs (
--     id uuid primary key,
--     user_id uuid null,
--     login_identifier varchar(150) not null,
--     outcome varchar(32) not null,
--     failure_reason varchar(64) null,
--     occurred_at timestamp not null,
--     source_ip varchar(64) null,
--     constraint fk_login_audit_user foreign key (user_id) references users (id)
-- );
--
-- create index idx_users_login_identifier on users (login_identifier);
-- create index idx_login_audit_login_identifier on login_audit_logs (login_identifier);


-- ============================================================
-- EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS btree_gist; -- EXCLUDE constraint với cột text + range

-- ============================================================
-- MODULE 5 (nền tảng): USERS & AUDIT
-- ============================================================
CREATE TABLE users (
                       id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                       login_identifier    text NOT NULL,
                       password_hash       text NOT NULL,
                       full_name           text,
                       role                text NOT NULL,
                       account_status      text NOT NULL DEFAULT 'active',
                       last_login_at       timestamptz,
                       created_at          timestamptz NOT NULL DEFAULT now(),
                       updated_at          timestamptz NOT NULL DEFAULT now(),
                       CONSTRAINT uq_users_login_identifier UNIQUE (login_identifier),
                       CONSTRAINT chk_users_role CHECK (role IN ('owner','salesperson','cashier')),
                       CONSTRAINT chk_users_account_status CHECK (account_status IN ('active','locked','disabled'))
);
COMMENT ON TABLE users IS 'Người dùng hệ thống: chủ / bán hàng / thu ngân';

CREATE TABLE login_audit_logs (
                                  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
                                  user_id             uuid,
                                  login_identifier    text NOT NULL,
                                  outcome             text NOT NULL,
                                  failure_reason      text,
                                  occurred_at         timestamptz NOT NULL DEFAULT now(),
                                  source_ip           inet,
                                  CONSTRAINT fk_login_audit_logs_user_id FOREIGN KEY (user_id)
                                      REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
                                  CONSTRAINT chk_login_audit_logs_outcome CHECK (outcome IN ('success','failure')),
                                  CONSTRAINT chk_login_audit_logs_failure_reason CHECK (
                                      failure_reason IS NULL
                                          OR failure_reason IN ('invalid_password','account_locked','account_disabled','unknown_identifier','other')
                                      )
);
COMMENT ON TABLE login_audit_logs IS 'Audit trail đăng nhập, append-only';

CREATE INDEX idx_login_audit_logs_user_id ON login_audit_logs (user_id);
CREATE INDEX idx_login_audit_logs_login_identifier ON login_audit_logs (login_identifier);
CREATE INDEX idx_login_audit_logs_occurred_at ON login_audit_logs (occurred_at);

-- ============================================================
-- MODULE 1: DANH MỤC SẢN PHẨM
-- ============================================================
CREATE TABLE rice_grades (
                             id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             grade_code      text NOT NULL,
                             grade_name      text NOT NULL,
                             description     text,
                             display_order   integer NOT NULL DEFAULT 0,
                             CONSTRAINT uq_rice_grades_grade_code UNIQUE (grade_code)
);

CREATE TABLE usage_purposes (
                                id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                purpose_code    text NOT NULL,
                                purpose_name    text NOT NULL,
                                CONSTRAINT uq_usage_purposes_purpose_code UNIQUE (purpose_code)
);

CREATE TABLE products (
                          id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          sku_code        text NOT NULL,
                          product_name    text NOT NULL,
                          grade_id        bigint NOT NULL,
                          origin          text,
                          unit_price      numeric(12,2) NOT NULL,
                          price_unit      text NOT NULL DEFAULT 'bao',
                          image_url       text,
                          is_active       boolean NOT NULL DEFAULT true,
                          created_at      timestamptz NOT NULL DEFAULT now(),
                          updated_at      timestamptz NOT NULL DEFAULT now(),
                          CONSTRAINT uq_products_sku_code UNIQUE (sku_code),
                          CONSTRAINT fk_products_grade_id FOREIGN KEY (grade_id)
                              REFERENCES rice_grades (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                          CONSTRAINT chk_products_unit_price CHECK (unit_price >= 0)
);

CREATE INDEX idx_products_grade_id ON products (grade_id);
CREATE INDEX idx_products_is_active ON products (is_active) WHERE is_active = true;

CREATE TABLE product_usage_purposes (
                                        product_id      bigint NOT NULL,
                                        purpose_id      bigint NOT NULL,
                                        CONSTRAINT pk_product_usage_purposes PRIMARY KEY (product_id, purpose_id),
                                        CONSTRAINT fk_product_usage_purposes_product_id FOREIGN KEY (product_id)
                                            REFERENCES products (id) ON DELETE CASCADE ON UPDATE CASCADE,
                                        CONSTRAINT fk_product_usage_purposes_purpose_id FOREIGN KEY (purpose_id)
                                            REFERENCES usage_purposes (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_product_usage_purposes_purpose_id ON product_usage_purposes (purpose_id);

-- ============================================================
-- MODULE 2: KHO & VỊ TRÍ
-- ============================================================
CREATE TABLE warehouse_zones (
                                 id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 zone_code       text NOT NULL,
                                 zone_name       text,
                                 CONSTRAINT uq_warehouse_zones_zone_code UNIQUE (zone_code)
);

CREATE TABLE warehouse_locations (
                                     id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     zone_id         bigint NOT NULL,
                                     location_code   text NOT NULL,
                                     description     text,
                                     CONSTRAINT fk_warehouse_locations_zone_id FOREIGN KEY (zone_id)
                                         REFERENCES warehouse_zones (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                     CONSTRAINT uq_warehouse_locations_zone_location UNIQUE (zone_id, location_code)
);

CREATE INDEX idx_warehouse_locations_zone_id ON warehouse_locations (zone_id);

CREATE TABLE inventory_lots (
                                id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                lot_code                    text NOT NULL,
                                product_id                  bigint NOT NULL,
                                grade_id                    bigint NOT NULL,
                                current_location_id         bigint NOT NULL,
                                quantity_bags_received      integer NOT NULL,
                                quantity_bags_remaining     integer NOT NULL,
                                unit_weight_kg              numeric(8,2),
                                unit_cost_per_bag           numeric(12,2) NOT NULL,
                                received_at                 timestamptz NOT NULL DEFAULT now(),
                                status                      text NOT NULL DEFAULT 'in_stock',
                                created_at                  timestamptz NOT NULL DEFAULT now(),
                                updated_at                  timestamptz NOT NULL DEFAULT now(),
                                CONSTRAINT uq_inventory_lots_lot_code UNIQUE (lot_code),
                                CONSTRAINT fk_inventory_lots_product_id FOREIGN KEY (product_id)
                                    REFERENCES products (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                CONSTRAINT fk_inventory_lots_grade_id FOREIGN KEY (grade_id)
                                    REFERENCES rice_grades (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                CONSTRAINT fk_inventory_lots_current_location_id FOREIGN KEY (current_location_id)
                                    REFERENCES warehouse_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                CONSTRAINT chk_inventory_lots_qty_received CHECK (quantity_bags_received > 0),
                                CONSTRAINT chk_inventory_lots_qty_remaining CHECK (quantity_bags_remaining >= 0),
                                CONSTRAINT chk_inventory_lots_qty_consistency CHECK (quantity_bags_remaining <= quantity_bags_received),
                                CONSTRAINT chk_inventory_lots_unit_weight CHECK (unit_weight_kg IS NULL OR unit_weight_kg > 0),
                                CONSTRAINT chk_inventory_lots_unit_cost CHECK (unit_cost_per_bag >= 0),
                                CONSTRAINT chk_inventory_lots_status CHECK (status IN ('in_stock','depleted','removed'))
);

CREATE INDEX idx_inventory_lots_product_id ON inventory_lots (product_id);
CREATE INDEX idx_inventory_lots_current_location_id ON inventory_lots (current_location_id);
CREATE INDEX idx_inventory_lots_grade_id ON inventory_lots (grade_id);
CREATE INDEX idx_inventory_lots_in_stock_by_product ON inventory_lots (product_id)
    WHERE status = 'in_stock';

CREATE TABLE inventory_lot_movements (
                                         id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         lot_id                  bigint NOT NULL,
                                         movement_type           text NOT NULL,
                                         from_location_id        bigint,
                                         to_location_id          bigint,
                                         quantity_bags           integer NOT NULL,
                                         performed_by            uuid NOT NULL,
                                         reference_note          text,
                                         occurred_at             timestamptz NOT NULL DEFAULT now(),
                                         CONSTRAINT fk_inventory_lot_movements_lot_id FOREIGN KEY (lot_id)
                                             REFERENCES inventory_lots (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                         CONSTRAINT fk_inventory_lot_movements_from_location_id FOREIGN KEY (from_location_id)
                                             REFERENCES warehouse_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                         CONSTRAINT fk_inventory_lot_movements_to_location_id FOREIGN KEY (to_location_id)
                                             REFERENCES warehouse_locations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                         CONSTRAINT fk_inventory_lot_movements_performed_by FOREIGN KEY (performed_by)
                                             REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                         CONSTRAINT chk_inventory_lot_movements_qty CHECK (quantity_bags > 0),
                                         CONSTRAINT chk_inventory_lot_movements_type CHECK (
                                             movement_type IN ('receipt','transfer','sale_out','adjustment')
                                             ),
                                         CONSTRAINT chk_inventory_lot_movements_locations CHECK (
                                             (movement_type = 'receipt'  AND from_location_id IS NULL     AND to_location_id IS NOT NULL) OR
                                             (movement_type = 'transfer' AND from_location_id IS NOT NULL AND to_location_id IS NOT NULL
                                                 AND from_location_id <> to_location_id) OR
                                             (movement_type = 'sale_out' AND to_location_id IS NULL) OR
                                             (movement_type = 'adjustment')
                                             )
);

CREATE INDEX idx_inventory_lot_movements_lot_id ON inventory_lot_movements (lot_id);
CREATE INDEX idx_inventory_lot_movements_performed_by ON inventory_lot_movements (performed_by);
CREATE INDEX idx_inventory_lot_movements_occurred_at ON inventory_lot_movements (occurred_at);

-- ============================================================
-- MODULE 4: KHÁCH HÀNG & CÔNG NỢ
-- ============================================================
CREATE TABLE customers (
                           id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           customer_name   text NOT NULL,
                           phone_number    text,
                           address         text,
                           created_at      timestamptz NOT NULL DEFAULT now(),
                           updated_at      timestamptz NOT NULL DEFAULT now(),
                           CONSTRAINT uq_customers_phone_number UNIQUE (phone_number)
);

-- ============================================================
-- MODULE 3 & 5: BÁN HÀNG
-- ============================================================
CREATE TABLE sales_orders (
                              id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              order_code      text NOT NULL,
                              customer_id     bigint,
                              order_status    text NOT NULL DEFAULT 'pending_payment',
                              payment_method  text,
                              created_by      uuid NOT NULL,
                              order_date      timestamptz NOT NULL DEFAULT now(),
                              total_amount    numeric(14,2) NOT NULL DEFAULT 0,
                              created_at      timestamptz NOT NULL DEFAULT now(),
                              updated_at      timestamptz NOT NULL DEFAULT now(),
                              CONSTRAINT uq_sales_orders_order_code UNIQUE (order_code),
                              CONSTRAINT fk_sales_orders_customer_id FOREIGN KEY (customer_id)
                                  REFERENCES customers (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                              CONSTRAINT fk_sales_orders_created_by FOREIGN KEY (created_by)
                                  REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                              CONSTRAINT chk_sales_orders_status CHECK (
                                  order_status IN ('draft','pending_payment','paid','cancelled')
                                  ),
                              CONSTRAINT chk_sales_orders_payment_method CHECK (
                                  payment_method IS NULL OR payment_method IN ('cash','bank_transfer','credit')
                                  ),
                              CONSTRAINT chk_sales_orders_total_amount CHECK (total_amount >= 0)
);

CREATE INDEX idx_sales_orders_customer_id ON sales_orders (customer_id);
CREATE INDEX idx_sales_orders_created_by ON sales_orders (created_by);
CREATE INDEX idx_sales_orders_order_date ON sales_orders (order_date);
CREATE INDEX idx_sales_orders_pending_payment ON sales_orders (order_date)
    WHERE order_status = 'pending_payment';

CREATE TABLE sales_order_items (
                                   id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   order_id        bigint NOT NULL,
                                   product_id      bigint NOT NULL,
                                   lot_id          bigint,
                                   quantity_bags   integer NOT NULL,
                                   unit_price      numeric(12,2) NOT NULL,
                                   line_total      numeric(14,2) GENERATED ALWAYS AS (quantity_bags * unit_price) STORED,
                                   created_at      timestamptz NOT NULL DEFAULT now(),
                                   CONSTRAINT fk_sales_order_items_order_id FOREIGN KEY (order_id)
                                       REFERENCES sales_orders (id) ON DELETE CASCADE ON UPDATE CASCADE,
                                   CONSTRAINT fk_sales_order_items_product_id FOREIGN KEY (product_id)
                                       REFERENCES products (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                   CONSTRAINT fk_sales_order_items_lot_id FOREIGN KEY (lot_id)
                                       REFERENCES inventory_lots (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                   CONSTRAINT chk_sales_order_items_qty CHECK (quantity_bags > 0),
                                   CONSTRAINT chk_sales_order_items_unit_price CHECK (unit_price >= 0)
);

CREATE INDEX idx_sales_order_items_order_id ON sales_order_items (order_id);
CREATE INDEX idx_sales_order_items_product_id ON sales_order_items (product_id);
CREATE INDEX idx_sales_order_items_lot_id ON sales_order_items (lot_id);

CREATE TABLE payments (
                          id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          order_id        bigint NOT NULL,
                          amount          numeric(14,2) NOT NULL,
                          payment_method  text NOT NULL,
                          confirmed_by    uuid NOT NULL,
                          paid_at         timestamptz NOT NULL DEFAULT now(),
                          CONSTRAINT fk_payments_order_id FOREIGN KEY (order_id)
                              REFERENCES sales_orders (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                          CONSTRAINT fk_payments_confirmed_by FOREIGN KEY (confirmed_by)
                              REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                          CONSTRAINT chk_payments_amount CHECK (amount > 0),
                          CONSTRAINT chk_payments_method CHECK (payment_method IN ('cash','bank_transfer'))
);

CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_payments_confirmed_by ON payments (confirmed_by);

-- customer_ledger_entries đặt sau sales_orders vì có FK tham chiếu order
CREATE TABLE customer_ledger_entries (
                                         id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         customer_id                 bigint NOT NULL,
                                         entry_amount                numeric(14,2) NOT NULL,
                                         entry_type                  text NOT NULL,
                                         reference_sales_order_id    bigint,
                                         note                        text NOT NULL,
                                         created_by                  uuid NOT NULL,
                                         created_at                  timestamptz NOT NULL DEFAULT now(),
                                         CONSTRAINT fk_customer_ledger_entries_customer_id FOREIGN KEY (customer_id)
                                             REFERENCES customers (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                         CONSTRAINT fk_customer_ledger_entries_order_id FOREIGN KEY (reference_sales_order_id)
                                             REFERENCES sales_orders (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                         CONSTRAINT fk_customer_ledger_entries_created_by FOREIGN KEY (created_by)
                                             REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                         CONSTRAINT chk_customer_ledger_entries_amount CHECK (entry_amount <> 0),
                                         CONSTRAINT chk_customer_ledger_entries_type CHECK (
                                             entry_type IN ('sale_on_credit','payment_received','adjustment','period_opening_balance')
                                             ),
                                         CONSTRAINT chk_customer_ledger_entries_ref_required CHECK (
                                             entry_type <> 'sale_on_credit' OR reference_sales_order_id IS NOT NULL
                                             )
);

CREATE INDEX idx_customer_ledger_entries_customer_id ON customer_ledger_entries (customer_id);
CREATE INDEX idx_customer_ledger_entries_created_at ON customer_ledger_entries (created_at);
CREATE INDEX idx_customer_ledger_entries_order_id ON customer_ledger_entries (reference_sales_order_id);

CREATE TABLE customer_ledger_period_closings (
                                                 id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 customer_id         bigint NOT NULL,
                                                 period_label        text NOT NULL,
                                                 closing_date        date NOT NULL,
                                                 closing_balance     numeric(14,2) NOT NULL,
                                                 generated_by        uuid NOT NULL,
                                                 created_at          timestamptz NOT NULL DEFAULT now(),
                                                 CONSTRAINT fk_customer_ledger_period_closings_customer_id FOREIGN KEY (customer_id)
                                                     REFERENCES customers (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                                 CONSTRAINT fk_customer_ledger_period_closings_generated_by FOREIGN KEY (generated_by)
                                                     REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                                 CONSTRAINT uq_customer_ledger_period_closings_customer_period UNIQUE (customer_id, period_label)
);

CREATE INDEX idx_customer_ledger_period_closings_customer_id
    ON customer_ledger_period_closings (customer_id);

-- ============================================================
-- MODULE 6: CỬU VẠN
-- ============================================================
CREATE TABLE porters (
                         id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name       text NOT NULL,
                         phone_number    text,
                         is_active       boolean NOT NULL DEFAULT true,
                         created_at      timestamptz NOT NULL DEFAULT now(),
                         CONSTRAINT uq_porters_phone_number UNIQUE (phone_number)
);

CREATE TABLE porter_labor_rates (
                                    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    rate_name       text NOT NULL,
                                    rate_per_bag    numeric(10,2),
                                    rate_per_km     numeric(10,2),
                                    effective_from  date NOT NULL,
                                    effective_to    date,
                                    CONSTRAINT chk_porter_labor_rates_rate_per_bag CHECK (rate_per_bag IS NULL OR rate_per_bag >= 0),
                                    CONSTRAINT chk_porter_labor_rates_rate_per_km CHECK (rate_per_km IS NULL OR rate_per_km >= 0),
                                    CONSTRAINT chk_porter_labor_rates_effective_range CHECK (
                                        effective_to IS NULL OR effective_to > effective_from
                                        ),
                                    CONSTRAINT excl_porter_labor_rates_no_overlap EXCLUDE USING gist (
        rate_name WITH =,
        daterange(effective_from, effective_to, '[]') WITH &&
    )
);

CREATE TABLE porter_trips (
                              id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              trip_code           text NOT NULL,
                              sales_order_id      bigint,
                              delivery_date       date NOT NULL,
                              destination         text NOT NULL,
                              distance_km         numeric(8,2),
                              rate_id             bigint NOT NULL,
                              total_bags          integer NOT NULL,
                              total_weight_kg     numeric(10,2),
                              computed_cost       numeric(12,2) NOT NULL,
                              created_at          timestamptz NOT NULL DEFAULT now(),
                              CONSTRAINT uq_porter_trips_trip_code UNIQUE (trip_code),
                              CONSTRAINT fk_porter_trips_sales_order_id FOREIGN KEY (sales_order_id)
                                  REFERENCES sales_orders (id) ON DELETE SET NULL ON UPDATE CASCADE,
                              CONSTRAINT fk_porter_trips_rate_id FOREIGN KEY (rate_id)
                                  REFERENCES porter_labor_rates (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                              CONSTRAINT chk_porter_trips_distance CHECK (distance_km IS NULL OR distance_km >= 0),
                              CONSTRAINT chk_porter_trips_total_bags CHECK (total_bags > 0),
                              CONSTRAINT chk_porter_trips_total_weight CHECK (total_weight_kg IS NULL OR total_weight_kg >= 0),
                              CONSTRAINT chk_porter_trips_computed_cost CHECK (computed_cost >= 0)
);

CREATE INDEX idx_porter_trips_sales_order_id ON porter_trips (sales_order_id);
CREATE INDEX idx_porter_trips_rate_id ON porter_trips (rate_id);
CREATE INDEX idx_porter_trips_delivery_date ON porter_trips (delivery_date);

CREATE TABLE porter_trip_workers (
                                     trip_id         bigint NOT NULL,
                                     porter_id       bigint NOT NULL,
                                     bags_handled    integer NOT NULL,
                                     CONSTRAINT pk_porter_trip_workers PRIMARY KEY (trip_id, porter_id),
                                     CONSTRAINT fk_porter_trip_workers_trip_id FOREIGN KEY (trip_id)
                                         REFERENCES porter_trips (id) ON DELETE CASCADE ON UPDATE CASCADE,
                                     CONSTRAINT fk_porter_trip_workers_porter_id FOREIGN KEY (porter_id)
                                         REFERENCES porters (id) ON DELETE RESTRICT ON UPDATE CASCADE,
                                     CONSTRAINT chk_porter_trip_workers_bags CHECK (bags_handled > 0)
);

CREATE INDEX idx_porter_trip_workers_porter_id ON porter_trip_workers (porter_id);

-- ============================================================
-- MODULE 7: THUẾ
-- ============================================================
CREATE TABLE tax_rates (
                           id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           tax_name        text NOT NULL,
                           rate_percent    numeric(5,2) NOT NULL,
                           effective_from  date NOT NULL,
                           effective_to    date,
                           CONSTRAINT chk_tax_rates_rate_percent CHECK (rate_percent >= 0 AND rate_percent <= 100),
                           CONSTRAINT chk_tax_rates_effective_range CHECK (
                               effective_to IS NULL OR effective_to > effective_from
                               ),
                           CONSTRAINT excl_tax_rates_no_overlap EXCLUDE USING gist (
        tax_name WITH =,
        daterange(effective_from, effective_to, '[]') WITH &&
    )
);

-- ============================================================
-- ÁP DỤNG APPEND-ONLY CHO SỔ CÁI CÔNG NỢ (Production hardening)
-- ============================================================
CREATE OR REPLACE FUNCTION fn_block_ledger_mutation()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'customer_ledger_entries là append-only: không được UPDATE/DELETE, chỉ được thêm bút toán mới';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_block_ledger_update
    BEFORE UPDATE ON customer_ledger_entries
    FOR EACH ROW EXECUTE FUNCTION fn_block_ledger_mutation();

CREATE TRIGGER trg_block_ledger_delete
    BEFORE DELETE ON customer_ledger_entries
    FOR EACH ROW EXECUTE FUNCTION fn_block_ledger_mutation();